<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <ProjectReference Include="..\CrowdControl.Application\CrowdControl.Application.csproj" />
    <ProjectReference Include="..\CrowdControl.Infrastructure.Persistence\CrowdControl.Infrastructure.Persistence.csproj" />
    <ProjectReference Include="..\CrowdControl.Infrastructure.Messaging\CrowdControl.Infrastructure.Messaging.csproj" />
    <ProjectReference Include="..\CrowdControl.Shared\CrowdControl.Shared.csproj" />
    <ProjectReference Include="..\CrowdControl.Dashboard\CrowdControl.Dashboard.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.Server" Version="10.0.12" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

</Project>
